name: Automatically deploy a set of artifacts from another actions

on: 
  workflow_call:

    inputs:

      CLUSTER_NAME:
        required: true
        type: string
      CLUSTER_RESOURCE_GROUP: 
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string

    secrets:
      AZ_CRED:
        required: true

jobs:

  deploy:
    name: DeployRobotshop
    runs-on: ubuntu-latest
    steps:
      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - id: setup_cluster_credentials
        uses: azure/aks-set-context@v1
        name: setupcluster
        with:
          creds: ${{ secrets.AZ_CRED }}
          cluster-name: ${{ inputs.CLUSTER_NAME }}
          resource-group: ${{ inputs.CLUSTER_RESOURCE_GROUP }}
          
      # Create namespace if doesn't exist
      - id: create_namespace
        name: createnamespace
        run: |
          kubectl create namespace ${{ inputs.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -    
    
      - id: install_helm
      # Deploy app to AKS using helm
        uses: azure/setup-helm@v3
        name: install_helm
        with:
          version: 'v3.5.4' # default is latest stable
          
      - id: install
        name: Helm install
        run: |
          helm repo add cloud-native-toolkit https://charts.cloudnativetoolkit.dev
          helm upgrade robot-shop --namespace ${NAMESPACE} --values https://github.com/billoreseema/demo_app/blob/ef97648c978ae53e1e82670ad10b5a8dd29dcc59/K8s/helm/values.yaml ./K8s/helm/  
      
      - id: helm_test
        name: Helm Test
        run: |
          helm test robot-shop --namespace ${NAMESPACE} --timeout 15m0s --logs
        continue-on-error: true
      
      - id: helm_rollback
        name: Helm Rollback
        if: steps.helm_test.outcome == 'failure'
        run: |
          echo "Rollback to previous version due to acceptance test cases issue"
          helm rollback ${CHART_NAME}-v1-${ENVIRONMENT} --namespace ${GKE_NAMESPACE} --timeout 15m
          kubectl rollout status Deployment/${CHART_NAME}-v1 --namespace=${GKE_NAMESPACE} --watch=true
          echo "===================================================================================================="
          echo "Rollback to previous version due to acceptance test cases issue so check the logs at HELM TEST STEP"
          echo "===================================================================================================="
          exit 1
