name: Chaos

on: 
  workflow_call:

    inputs:

      CLUSTER_NAME:
        required: true
        type: string
      CLUSTER_RESOURCE_GROUP: 
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string

    secrets:
      AZ_CRED:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - id: setup_cluster_credentials
      name: setup_cluster_credentials 
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZ_CRED }}
        cluster-name: ${{ inputs.CLUSTER_NAME }}
        resource-group: ${{ inputs.CLUSTER_RESOURCE_GROUP }}
      
    - id: print_cluster_info
      name: Print cluster information
      run: |
        kubectl config view
        kubectl cluster-info
        kubectl get nodes
        kubectl get pods -n kube-system
        helm version
        kubectl version
    - uses: actions/checkout@v2
        
    - id: run_chaos_test
      name: Run chaos mesh action
      uses: chaos-mesh/chaos-mesh-action@master
      env:
        CFG_BASE64: a2luZDogTmV0d29ya0NoYW9zCmFwaVZlcnNpb246IGNoYW9zLW1lc2gub3JnL3YxYWxwaGExCm1ldGFkYXRhOgogIG5hbWVzcGFjZTogcm9ib3Qtc2hvcAogIG5hbWU6IG5ldHdvcmstcm9ib3QKc3BlYzoKICBzZWxlY3RvcjoKICAgIG5hbWVzcGFjZXM6CiAgICAgIC0gcm9ib3Qtc2hvcAogIG1vZGU6IGFsbAogIGFjdGlvbjogZGVsYXkKICBkdXJhdGlvbjogNW0KICBkZWxheToKICAgIGxhdGVuY3k6IDEwcwogICAgY29ycmVsYXRpb246ICcwJwogICAgaml0dGVyOiAxMHMKICBkaXJlY3Rpb246IGJvdGgKICB0YXJnZXQ6CiAgICBzZWxlY3RvcjoKICAgICAgbmFtZXNwYWNlczoKICAgICAgICAtIHJvYm90LXNob3AKICAgIG1vZGU6IGFsbA==
        CHAOS_MESH_VERSION: v2.2.0
        CFG_FILE: https://raw.githubusercontent.com/chaos-mesh/chaos-mesh-action/master/chaos-test.yaml
