name: main_workflow

on: [ workflow_dispatch]

env:
  
  CLUSTER_NAME: DEMO-DEMO-SUA01-PROD-AKS
  CLUSTER_RESOURCE_GROUP: DEMO-DEMO-SUA01-PROD-RG
  NAMESPACE: robot-shop
  SECRET: azuresecret
  APP_NAME: robot-shop

jobs:

  deploy:
    name: Automatic Deploy    
    uses: ./.github/workflows/app.yml
    with:
      base-yaml: ./K8s/helm/values.yaml
      
  Inject:
      name: Deploy Sample app
      uses: ./.github/workflows/chaos-test.yml

  PerfTest:
      name: Run Perf application 
      uses: ./.github/workflows/perf.yml
