name: main_workflow

on: [ workflow_dispatch]

env:
  
  CLUSTER_NAME: DEMO-DEMO-SUA01-PROD-AKS
  CLUSTER_RESOURCE_GROUP: DEMO-DEMO-SUA01-PROD-RG
  NAMESPACE: robot-shop
  SECRET: azuresecret
  APP_NAME: robot-shop

jobs:

  deploy:
    name: Automatic Deploy    
    uses: ./.github/workflows/app.yml
    with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      
  Inject:
      name: Deploy Sample app
      uses: ./.github/workflows/chaos-test.yml
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
  PerfTest:
      name: Run Perf application 
      uses: ./.github/workflows/perf.yml
