name: main_workflow

on: [ workflow_dispatch]

env:
  
  CLUSTER_NAME: DEMO-DEMO-SUA01-PROD-AKS
  CLUSTER_RESOURCE_GROUP: DEMO-DEMO-SUA01-PROD-RG
  NAMESPACE: robot-shop
  SECRET: azuresecret
  APP_NAME: robot-shop

jobs:
  deploy:
    name: Automatic Deploy
    runs-on: ubuntu-latest
    
    steps:
      - id: repo_checkout
        name: Checkout
        uses: actions/checkout@v2
    
      - id: Deploy_App
        name: Deploy Sample application 
        uses: ./.github/workflows/app.yml
        with:
          base-yaml: ./K8s/helm/values.yaml
    
      - id: Inject_ChaosTest
        name: Deploy Sample application 
        uses: ./.github/workflows/chaos-test.yml

      - id: PerfTest
        name: Deploy Sample application 
        uses: ./.github/workflows/perf.yml
