name: Performance Test

on: 
  [workflow_call]

env:

  CLUSTER_NAME: DEMO-DEMO-SUA01-PROD-AKS
  CLUSTER_RESOURCE_GROUP: DEMO-DEMO-SUA01-PROD-RG
  NAMESPACE: robot-shop
  SECRET: azuresecret
  APP_NAME: robot-shop

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - uses: actions/checkout@v2
        
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ./robotshop.jmx
          outputReportsFolder: ./
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v1
        with:
          name: jmeter-results
          path: ./
