on: 
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'confirmatio'
        required: true
        
# Environment variables available to all jobs and steps in this workflow
env:
  
  CLUSTER_NAME: DEMO-DEMO-SUA01-PROD-AKS
  CLUSTER_RESOURCE_GROUP: DEMO-DEMO-SUA01-PROD-RG
  NAMESPACE: chaos-testing
  SECRET: azuresecret
  APP_NAME: chaos-mesh
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    
    # Deploy app to AKS using helm
    - uses: azure/setup-helm@v3
      with:
        version: 'v3.5.4' # default is latest stable
      id: install
    - run: |
        helm repo add chaos-mesh https://charts.chaos-mesh.org
        helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --version 2.2.2
